### ISSUE TITLE
Mejoras varias

### ISSUE THREAD

**Issue by SidVal** [mavillar/Raiola-manda-y-no-el-Panda#1]
- [ ] Aprovechá el readme, editalo y agrega encabezados y más texto ordenado.
Explica por qué existe el script, para qué sirve, etc... más texto :+1:  
- [ ] Crea Github pages para mejorar la presentación de tu script, y una nueva web bajo dominio "de cierta autoridad" que apunte a tu script ;-) 

***

Al margen, te felicito por la idea.
De las miles de cosas que leo sobre este concurso, esto ha sido lo más ORIGINAL :100:

**Comment by mavillar** [comment]
Muchas gracias SidVal por tu comentario.

Ya tengo varios blog apuntando al hilo de este repositorio. Lo que no sabía es lo de crear una página ni encabezados ni nada por el estilo. ¿Sabes de algún lado donde pueda aprender a hacerlo?

Gracias.

**Comment by SidVal** [comment]
Si no sabes cómo, empezá por lo básico.
Crea un repo test, y anda a "settings" del repositorio.
Más abajo, en las opciones, vas a ver algo de GitHub Pages.
Proba con ese repo test, así te sacas todas las dudas.
Luego, venis aca, haces lo mismo y generas el G-Pages.
Es bastante simple, pero tiene algunos truquitos si quieres darle dinamismo. (Aunque en esta oportunidad solo queres dejarlo estático para posicionamiento).

En cuanto a los estilos del readme, ahora te lo edito y ves en el Pull Request como hacer. 
También podes usar un editor de Markdown (https://stackedit.io/), y pasar las mejoras.

**Comment by mavillar** [comment]
Muchas gracias, agradezco tu ayuda.

**Comment by SidVal** [comment]
Fijate que tienes que editar tu [readme.md](https://github.com/mavillar/Raiola-manda-y-no-el-Panda/blob/master/README.md)., ya que en el último renglón no sabía a dónde enlazar por el soporte del script :+1:

**Comment by mavillar** [comment]
Buenas, no te preocupes, el link lo tengo arriba y acabo de cambiar el titulo y añadido otro detalle más.

**Comment by mavillar** [comment]
¿Eres de Argentina?

**Comment by SidVal** [comment]
Así es...
